### ISSUE TITLE
Error when cloning observation

### ISSUE THREAD

**Issue by rpiaggio** [gemini-hlsw/lucuma-odb#359]
When cloning an observation, the server throws: 
```
[ERROR] lucuma-odb - Error computing GraphQL response. 
skunk.exception.SkunkException: 
🔥  
🔥  Skunk encountered a problem related to use of begin
🔥    at «skunk internal»:0
🔥  
🔥    Problem: Nested transactions are not allowed.
🔥       Hint: You must roll back or commit the current transaction before starting
🔥             a new one.
🔥  

skunk.exception.SkunkException: Nested transactions are not allowed.
	at skunk.Transaction$.assertIdle$1$$anonfun$1(Transaction.scala:107)
	at cats.data.Kleisli.flatMap$$anonfun$2$$anonfun$1(Kleisli.scala:75)
	at cats.effect.IOFiber.succeeded(IOFiber.scala:1177)
	at cats.effect.IOFiber.runLoop(IOFiber.scala:247)
	at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1330)
	at cats.effect.IOFiber.run(IOFiber.scala:119)
	at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:485)
```

Invoked mutation:
```graphql
mutation ($input: CloneObservationInput!){
  cloneObservation(input: $input) {
        newObservation 
        {
          id
          title
          subtitle
          status
          activeStatus
          visualizationTime
          posAngleConstraint 
        {
          mode
          angle 
        {
          microarcseconds
        }
      
        }
      
          plannedTime {
            execution 
        {
          microseconds
        }
      
          }
          targetEnvironment {
            asterism {
              id
            }
          }
          constraintSet 
        {
          cloudExtinction
          imageQuality
          skyBackground
          waterVapor          elevationRange {
            airMass {
              min
              max
            }
            hourAngle {
              minHours
              maxHours
            }
          }
        }
      
          scienceRequirements {
            spectroscopy {
              wavelength 
        {
          picometers
        }
      
            }
          }
          observingMode 
        {
          gmosNorthLongSlit {
            grating
            filter
            fpu
            centralWavelength 
        {
          picometers
        }
      
          }
          gmosSouthLongSlit {
            grating
            filter
            fpu
            centralWavelength 
        {
          picometers
        }
      
          }
        }
      
        }
      
          }
        }
```
```json
{
  "input" : {
    "observationId" : "o-102"
    "SET" : {
      "targetEnvironment" : {
        "asterism" : [
          "t-103"
        ]
      }
    }
  }
}
```

(Sorry for the weird indentation)

**Comment by toddburnside** [comment]
The error has changed, but the problem remains. The clone is successful, but the request returns an error and this shows up in the log:
 

> [WARN ] lucuma-odb - u-10c/Todd Burnside: Internal error: Throwable: Expected single value for field 'id' of type Observation at List(newObservation, cloneObservation), found many 
> [ERROR] lucuma-odb - Error computing GraphQL response. 
> java.lang.Throwable: Expected single value for field 'id' of type Observation at List(newObservation, cloneObservation), found many

**Comment by toddburnside** [comment]
More information: The error doesn't occur if the response query only contains fields from the observation itself. But, it does occur if you request fields from child objects. For example:

```
mutation {
  cloneObservation(
    input: {
      observationId: "o-100"
    }
  ) {
    newObservation {
      id
      targetEnvironment {
        asterism {
          id
        }
      }
    }
  }
}
```

It seems like it might be having an issue because there is an old id and a new id available?
