### ISSUE TITLE
Setting `parentGroupId` on a group that already doesn't have a parentGroupId causes PostgresException

### ISSUE THREAD

**Issue by hugo-vrijswijk** [gemini-hlsw/lucuma-odb#429]
```graphql
mutation($input: UpdateGroupsInput) {
  updateGroups(input:$input) {
    groups {
      id
    }
  }
}
```

Variables:
```json
{
  "input": {
    "WHERE": {
      "id": {
        "EQ": "g-103"
      }
    },
    "SET": {
      "parentGroup": null
    }
  }
}
```

If the group is in a group, this will run fine the first time, but running it again causes a PostgresException. 

Stack:
```
skunk.exception.SkunkException: Just constructed an unknown completion 'SET CONSTRAINTS'.  Note that your program has not crashed. This message is here to annoy you.
 at skunk.data.Completion$Unknown.<init>(Completion.scala:62)
 at skunk.data.Completion$Unknown$.apply(Completion.scala:61)
 at skunk.net.message.CommandComplete$.decoder$$anonfun$1(CommandComplete.scala:95)
 at scodec.DecodeResult.map(DecodeResult.scala:40)
 at scodec.Decoder$$anon$1.decode$$anonfun$1(Decoder.scala:58)
 at scodec.Attempt$Successful.map(Attempt.scala:129)
 at scodec.Decoder$$anon$1.decode(Decoder.scala:58)
 at scodec.Decoder.decodeValue(Decoder.scala:53)
 at scodec.Decoder.decodeValue$(Decoder.scala:39)
 at scodec.Decoder$$anon$1.decodeValue(Decoder.scala:57)
 at skunk.net.MessageSocket$.$init$$$anonfun$1$$anonfun$1(MessageSocket.scala:61)
 at cats.Monad.map$$anonfun$1(Monad.scala:35)
 at cats.data.Kleisli.flatMap$$anonfun$2$$anonfun$1(Kleisli.scala:75)
 at cats.effect.IOFiber.succeeded(IOFiber.scala:1170)
 at cats.effect.IOFiber.runLoop(IOFiber.scala:240)
 at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1323)
 at cats.effect.IOFiber.run(IOFiber.scala:113)
 at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:555)
 [ERROR] lucuma-odb - Error computing GraphQL response.
skunk.exception.PostgresErrorException:
🔥
🔥  Postgres ERROR P0001 raised in exec_stmt_raise (pl_exec.c:3893)
🔥
🔥    Problem: Index discontinuity detected in the top-level group..
```

**Comment by hugo-vrijswijk** [comment]
This has been fixed
