### ISSUE TITLE
Internal error on CloneObservationInput

### ISSUE THREAD

**Issue by cquiroz** [gemini-hlsw/lucuma-odb#448]
a query to add an obs to a target end with an internal error messagge

the query is:
```graphql

        mutation ($input: CloneObservationInput!){
          cloneObservation(input: $input) {
            newObservation 
        {
          id
          title
          subtitle
          status
          activeStatus
          visualizationTime
          posAngleConstraint 
        {
          mode
          angle 
        {
          microarcseconds
        }
      
        }
      
          plannedTime {
            execution 
        {
          microseconds
        }
      
          }
          targetEnvironment {
            asterism {
              id
            }
          }
          constraintSet 
        {
          cloudExtinction
          imageQuality
          skyBackground
          waterVapor
          elevationRange {
            airMass {
              min
              max
            }
            hourAngle {
              minHours
              maxHours
            }
          }
        }
      
          timingWindows 
        {
          inclusion
          startUtc
          end {
            ... on TimingWindowEndAt {
              atUtc
            }
            ... on TimingWindowEndAfter {
              after {
                milliseconds
              }         
              repeat {
                period {
                  milliseconds
                }
                times
              }
            }
          }
        }
      
          scienceRequirements {
            spectroscopy {
              wavelength 
        {
          picometers
        }
      
              resolution
              signalToNoise
              signalToNoiseAt 
        {
          picometers
        }
      
              wavelengthCoverage 
        {
          picometers
        }
      
              focalPlane
              focalPlaneAngle 
        {
          microarcseconds
        }
      
              capability
            }
          }
          observingMode 
        {
          gmosNorthLongSlit {
            initialGrating
            initialFilter
            initialFpu
            initialCentralWavelength 
        {
          picometers
        }
      
            grating
            filter
            fpu
            centralWavelength 
        {
          picometers
        }
      
            defaultXBin
            explicitXBin
            defaultYBin
            explicitYBin
            defaultAmpReadMode
            explicitAmpReadMode
            defaultAmpGain
            explicitAmpGain
            defaultRoi
            explicitRoi
            defaultWavelengthDithers 
        {
          picometers
        }
      
            explicitWavelengthDithers 
        {
          picometers
        }
      
            defaultSpatialOffsets 
        {
          microarcseconds
        }
      
            explicitSpatialOffsets 
        {
          microarcseconds
        }
      
          }
          gmosSouthLongSlit {
            initialGrating
            initialFilter
            initialFpu
            initialCentralWavelength 
        {
          picometers
        }
      
            grating
            filter
            fpu
            centralWavelength 
        {
          picometers
        }
      
            defaultXBin
            explicitXBin
            defaultYBin
            explicitYBin
            defaultAmpReadMode
            explicitAmpReadMode
            defaultAmpGain
            explicitAmpGain
            defaultRoi
            explicitRoi
            defaultWavelengthDithers 
        {
          picometers
        }
      
            explicitWavelengthDithers 
        {
          picometers
        }
      
            defaultSpatialOffsets 
        {
          microarcseconds
        }
      
            explicitSpatialOffsets 
        {
          microarcseconds
        }
      
          }
        }
      
        }
      
          }
        }
      
```
and variables:
```json
{
  "input": {
    "observationId": "o-129",
    "SET": {
      "targetEnvironment": {
        "asterism": [
          "t-4f0"
        ]
      }
    }
  }
}
```

**Comment by cquiroz** [comment]
On the backend we see this stack trace
```
2023-05-23T14:39:35.772719+00:00 app[web.2]: skunk.exception.SkunkException: Nested transactions are not allowed.
2023-05-23T14:39:35.772915+00:00 app[web.2]: [ERROR] lucuma-odb - Error computing GraphQL response.
2023-05-23T14:39:35.772915+00:00 app[web.2]: skunk.exception.SkunkException:
2023-05-23T14:39:35.772915+00:00 app[web.2]: :fire:
2023-05-23T14:39:35.772915+00:00 app[web.2]: :fire:  Skunk encountered a problem related to use of begin
2023-05-23T14:39:35.772915+00:00 app[web.2]: :fire:    at «skunk internal»:0
2023-05-23T14:39:35.772915+00:00 app[web.2]: :fire:
2023-05-23T14:39:35.772916+00:00 app[web.2]: :fire:    Problem: Nested transactions are not allowed.
2023-05-23T14:39:35.772916+00:00 app[web.2]: :fire:       Hint: You must roll back or commit the current transaction before starting
2023-05-23T14:39:35.772916+00:00 app[web.2]: :fire:             a new one.
2023-05-23T14:39:35.772916+00:00 app[web.2]: :fire:
2023-05-23T14:39:35.772917+00:00 app[web.2]: 
2023-05-23T14:39:35.772917+00:00 app[web.2]: skunk.exception.SkunkException: Nested transactions are not allowed.
2023-05-23T14:39:35.772917+00:00 app[web.2]: at skunk.Transaction$.assertIdle$1$$anonfun$1(Transaction.scala:107)
2023-05-23T14:39:35.772917+00:00 app[web.2]: at cats.data.Kleisli.flatMap$$anonfun$2$$anonfun$1(Kleisli.scala:75)
2023-05-23T14:39:35.772918+00:00 app[web.2]: at cats.effect.IOFiber.succeeded(IOFiber.scala:1190)
2023-05-23T14:39:35.772918+00:00 app[web.2]: at cats.effect.IOFiber.runLoop(IOFiber.scala:240)
2023-05-23T14:39:35.772918+00:00 app[web.2]: at cats.effect.IOFiber.asyncContinueSuccessfulR(IOFiber.scala:1358)
2023-05-23T14:39:35.772918+00:00 app[web.2]: at cats.effect.IOFiber.run(IOFiber.scala:113)
2023-05-23T14:39:35.772918+00:00 app[web.2]: at cats.effect.unsafe.WorkerThread.run(WorkerThread.scala:721)
```

**Comment by tpolecat** [comment]
Ok, I'm actually working on that right now.
