### ISSUE TITLE
`GmosCustomMask` mapping

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/lucuma-odb#513]
PR #512 adds the GMOS dynamic config to step records.  The `GmosCustomMask` mapping warrants a review.  `GmosDynamicTables` required `.opt` fields where `.embedded` is expected:

```scala
    // FPU (custom or builtin or none)
    object Fpu {
      val CustomMaskFilename: ColumnRef  = col("c_fpu_custom_mask_filename",   varchar.opt)
      val CustomMaskSlitWidth: ColumnRef = col("c_fpu_custom_mask_slit_width", gmos_custom_slit_width.opt)
      val Builtin: ColumnRef             = col("c_fpu_builtin",                fpu.opt)
    }
```

and a `SwitchMapping` for `GmosCustomMask` along the lines of the one for `GmosCcdMode` generates an `AssertionError`:

```
ava.lang.AssertionError: assertion failed
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
	at edu.gemini.grackle.sql.SqlMappingLike.mkCursorForField$$anonfun$2$$anonfun$1(SqlMapping.scala:741)
	at edu.gemini.grackle.Result.map(result.scala:30)
	at edu.gemini.grackle.Result.map$(result.scala:19)
	at edu.gemini.grackle.Result$Success.map(result.scala:151)
	at edu.gemini.grackle.sql.SqlMappingLike.mkCursorForField$$anonfun$2(SqlMapping.scala:742)
	at edu.gemini.grackle.Result.flatMap(result.scala:38)
	at edu.gemini.grackle.Result.flatMap$(result.scala:19)
	at edu.gemini.grackle.Result$Success.flatMap(result.scala:151)
	at edu.gemini.grackle.sql.SqlMappingLike.mkCursorForField(SqlMapping.scala:743)
	at edu.gemini.grackle.sql.SqlMappingLike.mkCursorForField$(SqlMapping.scala:26)
	at edu.gemini.grackle.skunk.SkunkMapping.mkCursorForField(SkunkMapping.scala:21)
	at edu.gemini.grackle.sql.SqlMappingLike$SqlCursor.field(SqlMapping.scala:3464)
	at edu.gemini.grackle.QueryInterpreter.runFields(queryinterpreter.scala:229)
	at edu.gemini.grackle.QueryInterpreter.runFields$$anonfun$9(queryinterpreter.scala:258)
```

In short, there's something odd about the GMOS FPU masking and we should experiment with sequences that use a custom mask.

**Comment by swalker2m** [comment]
Fixed by #514
